server:
  port: 8080
spring:
  application:
    name: eatGo-gateway
  cloud:
    nacos:
      server-addr: 192.168.174.130:8848
    gateway:
      routes:
        - id: user # 路由规则id，自定义，唯一
          uri: lb://user-service # 路由的目标服务，lb代表负载均衡，会从注册中心拉取服务列表
          predicates: # 路由断言，判断当前请求是否符合当前规则，符合则路由到目标服务
            - Path=/user/** # 这里是以请求路径作为判断规则
        - id: email # 路由规则id，自定义，唯一
          uri: lb://email-service # 路由的目标服务，lb代表负载均衡，会从注册中心拉取服务列表
          predicates: # 路由断言，判断当前请求是否符合当前规则，符合则路由到目标服务
            - Path=/mail/** # 这里是以请求路径作为判断规则
