server:
  port: 8080
spring:
  application:
    name: eatGo-gateway
  cloud:
    nacos:
      server-addr: 192.168.174.130:8848
    sentinel:
      transport:
        dashboard: 192.168.174.130:9090
      http-method-specify: true
    gateway:
      routes:
        - id: user
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: email
          uri: lb://email-service
          predicates:
            - Path=/mail/**
        - id: menu
          uri: lb://menu-service
          predicates:
            - Path=/menu/**
        - id: collection
          uri: lb://collection-service
          predicates:
            - Path=/collection/**
        - id: fund
          uri: lb://fund-service
          predicates:
            - Path=/fund/**
        - id: comment
          uri: lb://comment-service
          predicates:
            - Path=/comment/**
        - id: order
          uri: lb://order-service
          predicates:
            - Path=/order/**



