spring:
  application:
    name: email-service
  cloud:
    nacos:
      server-addr: 192.168.174.130:8848

  mail:
    username: 13929944553@163.com
    password: RHSzTpKJ3EBZvqhF
    host: smtp.163.com

server:
  port: 9001
