spring:
  application:
    name: menu-service
  profiles:
    active: dev

  cloud:
    nacos:
      server-addr: 192.168.174.130:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://${mysql.connect.url}:3306/menu
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${mysql.connect.username}
    password: ${mysql.connect.password}

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

server:
  port: 9003